# Generated by Django 2.2.4 on 2020-02-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cihaz adını giriniz', max_length=60, verbose_name='Cihaz adı')),
                ('field_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alan 1')),
                ('field_id_1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alan ID 1')),
                ('field_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alan 2')),
                ('field_id_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alan ID 2')),
                ('field_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alan 3')),
                ('field_id_3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alan ID 3')),
                ('field_4', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alan 4')),
                ('field_id_4', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alan ID 4')),
                ('field_5', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alan 5')),
                ('field_id_5', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alan ID 5')),
                ('field_6', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alan 6')),
                ('field_id_6', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alan ID 6')),
                ('field_7', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alan 7')),
                ('field_id_7', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alan ID 7')),
                ('field_8', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alan 8')),
                ('field_id_8', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alan ID 8')),
                ('field_9', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alan 9')),
                ('field_id_9', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alan ID 9')),
                ('field_10', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alan 10')),
                ('field_id_10', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alan ID 10')),
                ('api_key', models.CharField(max_length=200, verbose_name='Api key')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('enable', models.BooleanField(default=True, verbose_name='Aktif et')),
                ('remote_address', models.CharField(max_length=255, verbose_name='Ip adres')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Yayin tarihi')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
