# Generated by Django 2.2.4 on 2020-02-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='device',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Activate'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Area 1'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_10',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Area 10'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Area 2'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Area 3'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Area 4'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Area 5'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_6',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Area 6'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_7',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Area 7'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_8',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Area 8'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_9',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Area 9'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_id_1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Area ID 1'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_id_10',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Area ID 10'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_id_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Area ID 2'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_id_3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Area ID 3'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_id_4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Area ID 4'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_id_5',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Area ID 5'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_id_6',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Area ID 6'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_id_7',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Area ID 7'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_id_8',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Area ID 8'),
        ),
        migrations.AlterField(
            model_name='device',
            name='field_id_9',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Area ID 9'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='Enter the device name', max_length=60, verbose_name='Device name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='device',
            name='remote_address',
            field=models.CharField(max_length=255, verbose_name='IP address'),
        ),
    ]
