# Generated by Django 2.2.4 on 2020-02-03 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(max_length=10, null=True, verbose_name='Deger 1')),
                ('field_2', models.CharField(max_length=10, null=True, verbose_name='Deger 2')),
                ('field_3', models.CharField(max_length=10, null=True, verbose_name='Deger 3')),
                ('field_4', models.CharField(max_length=10, null=True, verbose_name='Deger 4')),
                ('field_5', models.CharField(max_length=10, null=True, verbose_name='Deger 5')),
                ('field_6', models.CharField(max_length=10, null=True, verbose_name='Deger 6')),
                ('field_7', models.CharField(max_length=10, null=True, verbose_name='Deger 7')),
                ('field_8', models.CharField(max_length=10, null=True, verbose_name='Deger 8')),
                ('field_9', models.CharField(max_length=10, null=True, verbose_name='Deger 9')),
                ('field_10', models.CharField(max_length=10, null=True, verbose_name='Deger 10')),
                ('api_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='Api key')),
                ('remote_address', models.CharField(max_length=255, verbose_name='Ip adres')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Yayin tarihi')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_data', to='devices.Device')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
