# Generated by Django 2.2.4 on 2020-02-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='field_1',
            field=models.CharField(max_length=10, null=True, verbose_name='Value 1'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_10',
            field=models.CharField(max_length=10, null=True, verbose_name='Value 10'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_2',
            field=models.CharField(max_length=10, null=True, verbose_name='Value 2'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_3',
            field=models.CharField(max_length=10, null=True, verbose_name='Value 3'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_4',
            field=models.CharField(max_length=10, null=True, verbose_name='Value 4'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_5',
            field=models.CharField(max_length=10, null=True, verbose_name='Value 5'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_6',
            field=models.CharField(max_length=10, null=True, verbose_name='Value 6'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_7',
            field=models.CharField(max_length=10, null=True, verbose_name='Value 7'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_8',
            field=models.CharField(max_length=10, null=True, verbose_name='Value 8'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_9',
            field=models.CharField(max_length=10, null=True, verbose_name='Value 9'),
        ),
        migrations.AlterField(
            model_name='data',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='data',
            name='remote_address',
            field=models.CharField(max_length=255, verbose_name='IP address'),
        ),
    ]
